<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
		'key' => 'group_56fd60ab71f04',
		'title' => 'Gerenciamento de conteudo',
		'fields' => array (
				array (
						'key' => 'field_56fd60babf0ac',
						'label' => 'Logo',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
				),
				array (
						'key' => 'field_56fd61e522a76',
						'label' => 'Logo',
						'name' => 'logo_home',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
				),
				array (
						'key' => 'field_56fd613bbf0ad',
						'label' => 'Redes Sociais',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
				),
				array (
						'key' => 'field_56fd6158bf0ae',
						'label' => 'Facebook',
						'name' => 'facebook_home',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
				),
				array (
						'key' => 'field_56fd6182bf0af',
						'label' => 'Youtube',
						'name' => 'youtube_home',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
				),
				array (
						'key' => 'field_56fd6195bf0b0',
						'label' => 'Twitter',
						'name' => 'twitter_home',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
				),
				array (
						'key' => 'field_56fd61adbf0b1',
						'label' => 'Instagram',
						'name' => 'instagram_home',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
				),
		),
		'location' => array (
				array (
						array (
								'param' => 'options_page',
								'operator' => '==',
								'value' => 'gerenciamento-de-conteudo',
						),
				),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
));
acf_add_local_field_group(array (
		'key' => 'group_56fd6d83b4a56',
		'title' => 'Banner',
		'fields' => array (
				array (
						'key' => 'field_56fd6e33df157',
						'label' => 'Banner',
						'name' => 'banner_home',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
						),
						'min' => '',
						'max' => '',
						'layout' => 'table',
						'button_label' => 'Adicionar imagem',
						'sub_fields' => array (
								array (
										'key' => 'field_56fd6e4cdf158',
										'label' => 'Imagem',
										'name' => 'imagem_banner',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
								),
								array (
										'key' => 'field_56fd6e61df159',
										'label' => 'Titulo',
										'name' => 'titulo_banner',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'readonly' => 0,
										'disabled' => 0,
								),
								array (
										'key' => 'field_56fd6e77df15a',
										'label' => 'Url',
										'name' => 'url_banner',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
								),
						),
				),
		),
		'location' => array (
				array (
						array (
								'param' => 'options_page',
								'operator' => '==',
								'value' => 'acf-options-banner',
						),
				),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
));
endif;


?>